"""
Virtual Machine for the language.
Executes bytecode generated by the compiler.
"""
from compiler import Opcode, Bytecode

class VM:
    """Virtual Machine for executing bytecode."""
    def __init__(self, code, constants):
        self.code = code
        self.constants = constants
        self.stack = []
        self.variables = {}
        self.ip = 0  # Instruction pointer
        self.call_stack = []  # For function calls
    
    def run(self):
        """Execute the bytecode."""
        while self.ip < len(self.code):
            instr = self.code[self.ip]
            self.ip += 1
            
            try:
                self._execute(instr)
            except Exception as e:
                print(f"Runtime error at instruction {self.ip-1} ({instr}): {e}")
                break
    
    def _execute(self, instr):
        """Execute a single instruction."""
        opcode = instr.opcode
        args = instr.args
        
        if opcode == Opcode.PUSH_CONST:
            const_index = args[0]
            self.stack.append(self.constants[const_index])
        
        elif opcode == Opcode.PUSH_NULL:
            self.stack.append(None)
        
        elif opcode == Opcode.PUSH_TRUE:
            self.stack.append(True)
        
        elif opcode == Opcode.PUSH_FALSE:
            self.stack.append(False)
        
        elif opcode == Opcode.LOAD_VAR:
            var_index = args[0]
            var_name = self._get_variable_name(var_index)
            if var_name not in self.variables:
                raise NameError(f"Undefined variable: {var_name}")
            self.stack.append(self.variables[var_name])
        
        elif opcode == Opcode.STORE_VAR:
            var_index = args[0]
            var_name = self._get_variable_name(var_index)
            if var_name not in self.variables:
                raise NameError(f"Undefined variable: {var_name}")
            if not self.stack:
                raise RuntimeError("Stack underflow")
            value = self.stack.pop()
            self.variables[var_name] = value
        
        elif opcode == Opcode.DEFINE_VAR:
            var_index = args[0]
            var_name = self._get_variable_name(var_index)
            if not self.stack:
                raise RuntimeError("Stack underflow")
            value = self.stack.pop()
            self.variables[var_name] = value
        
        elif opcode == Opcode.ADD:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            
            # Type checking
            if isinstance(left, str) and isinstance(right, str):
                self.stack.append(left + right)
            elif isinstance(left, (int, float)) and isinstance(right, (int, float)):
                self.stack.append(left + right)
            else:
                raise TypeError(f"Cannot add {type(left).__name__} and {type(right).__name__}")
        
        elif opcode == Opcode.SUB:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            
            if not (isinstance(left, (int, float)) and isinstance(right, (int, float))):
                raise TypeError(f"Cannot subtract {type(left).__name__} and {type(right).__name__}")
            
            self.stack.append(left - right)
        
        elif opcode == Opcode.MUL:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            
            if not (isinstance(left, (int, float)) and isinstance(right, (int, float))):
                raise TypeError(f"Cannot multiply {type(left).__name__} and {type(right).__name__}")
            
            self.stack.append(left * right)
        
        elif opcode == Opcode.DIV:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            
            if not (isinstance(left, (int, float)) and isinstance(right, (int, float))):
                raise TypeError(f"Cannot divide {type(left).__name__} and {type(right).__name__}")
            
            if right == 0:
                raise ZeroDivisionError("Division by zero")
            
            self.stack.append(left / right)
        
        elif opcode == Opcode.NEG:
            if not self.stack:
                raise RuntimeError("Stack underflow")
            value = self.stack.pop()
            
            if not isinstance(value, (int, float)):
                raise TypeError(f"Cannot negate {type(value).__name__}")
            
            self.stack.append(-value)
        
        elif opcode == Opcode.EQ:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            self.stack.append(left == right)
        
        elif opcode == Opcode.NE:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            self.stack.append(left != right)
        
        elif opcode == Opcode.LT:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            
            if not (type(left) == type(right) and isinstance(left, (int, float, str))):
                raise TypeError(f"Cannot compare {type(left).__name__} and {type(right).__name__}")
            
            self.stack.append(left < right)
        
        elif opcode == Opcode.GT:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            
            if not (type(left) == type(right) and isinstance(left, (int, float, str))):
                raise TypeError(f"Cannot compare {type(left).__name__} and {type(right).__name__}")
            
            self.stack.append(left > right)
        
        elif opcode == Opcode.LE:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            
            if not (type(left) == type(right) and isinstance(left, (int, float, str))):
                raise TypeError(f"Cannot compare {type(left).__name__} and {type(right).__name__}")
            
            self.stack.append(left <= right)
        
        elif opcode == Opcode.GE:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            
            if not (type(left) == type(right) and isinstance(left, (int, float, str))):
                raise TypeError(f"Cannot compare {type(left).__name__} and {type(right).__name__}")
            
            self.stack.append(left >= right)
        
        elif opcode == Opcode.NOT:
            if not self.stack:
                raise RuntimeError("Stack underflow")
            value = self.stack.pop()
            self.stack.append(not self._is_truthy(value))
        
        elif opcode == Opcode.AND:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            self.stack.append(self._is_truthy(left) and self._is_truthy(right))
        
        elif opcode == Opcode.OR:
            if len(self.stack) < 2:
                raise RuntimeError("Stack underflow")
            right = self.stack.pop()
            left = self.stack.pop()
            self.stack.append(self._is_truthy(left) or self._is_truthy(right))
        
        elif opcode == Opcode.JUMP:
            label = args[0]
            # In a real implementation, we'd look up the label address
            # For now, we'll just skip this instruction
            pass
        
        elif opcode == Opcode.JUMP_IF_FALSE:
            label = args[0]
            if not self.stack:
                raise RuntimeError("Stack underflow")
            condition = self.stack.pop()
            if not self._is_truthy(condition):
                # In a real implementation, we'd jump to the label
                pass
        
        elif opcode == Opcode.JUMP_IF_TRUE:
            label = args[0]
            if not self.stack:
                raise RuntimeError("Stack underflow")
            condition = self.stack.pop()
            if self._is_truthy(condition):
                # In a real implementation, we'd jump to the label
                pass
        
        elif opcode == Opcode.CALL:
            # TODO: Implement function calls
            raise NotImplementedError("Function calls not yet implemented")
        
        elif opcode == Opcode.RETURN:
            # TODO: Implement returns
            raise NotImplementedError("Returns not yet implemented")
        
        elif opcode == Opcode.PRINT:
            if not self.stack:
                raise RuntimeError("Stack underflow")
            value = self.stack.pop()
            print(self._stringify(value))
        
        elif opcode == Opcode.BUILD_LIST:
            count = args[0]
            if len(self.stack) < count:
                raise RuntimeError("Stack underflow")
            
            elements = []
            for _ in range(count):
                elements.insert(0, self.stack.pop())  # Reverse order
            
            self.stack.append(elements)
        
        else:
            raise RuntimeError(f"Unknown opcode: {opcode}")
    
    def _get_variable_name(self, index):
        """Get variable name from index (simplified)."""
        # In a real implementation, we'd have a mapping
        # For now, we'll use a simple approach
        for name, idx in self.variables.items():
            if idx == index:
                return name
        return f"var_{index}"
    
    def _is_truthy(self, value):
        """Determine if a value is truthy."""
        if value is None:
            return False
        elif isinstance(value, bool):
            return value
        elif isinstance(value, (int, float)):
            return value != 0
        elif isinstance(value, str):
            return len(value) > 0
        elif isinstance(value, list):
            return len(value) > 0
        else:
            return True
    
    def _stringify(self, value):
        """Convert a value to a string for printing."""
        if value is None:
            return "null"
        elif isinstance(value, bool):
            return "true" if value else "false"
        elif isinstance(value, list):
            items = [self._stringify(item) for item in value]
            return f"[{', '.join(items)}]"
        else:
            return str(value)

def run_bytecode(code, constants):
    """Convenience function to run bytecode."""
    vm = VM(code, constants)
    vm.run()

if __name__ == '__main__':
    # Test the VM with a simple program
    from compiler import compile_source
    
    test_code = """
    let x = 10;
    print(x * 2);
    """
    
    print("Testing VM with code:")
    print(test_code)
    
    code, constants = compile_source(test_code)
    
    print("\nRunning VM...")
    run_bytecode(code, constants)